# Generated by Django 5.0.1 on 2024-02-28 14:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_name', models.CharField(blank=True, max_length=100, null=True)),
                ('author_university', models.CharField(blank=True, max_length=100, null=True)),
                ('author_uni_url', models.URLField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=200)),
                ('university_country', models.CharField(max_length=250)),
                ('university_url', models.URLField()),
                ('research_group', models.CharField(max_length=100)),
                ('research_group_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_title', models.CharField(max_length=200)),
                ('pages', models.CharField(max_length=10)),
                ('uploaded_file', models.FileField(upload_to='papers/')),
                ('secret_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('authors', models.ManyToManyField(to='workshops.author')),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_title', models.CharField(max_length=200)),
                ('workshop_description', models.CharField(max_length=500)),
                ('workshop_location', models.CharField(max_length=200)),
                ('workshop_begin_date', models.DateField()),
                ('workshop_end_date', models.DateField()),
                ('submitted_by', models.CharField(max_length=200)),
                ('volume_number', models.CharField(max_length=10)),
                ('urn', models.CharField(max_length=50)),
                ('publication_year', models.IntegerField()),
                ('license', models.CharField(max_length=50)),
                ('location_time', models.CharField(max_length=200)),
                ('secret_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('accepted_papers', models.ManyToManyField(related_name='accepted_papers', to='workshops.paper')),
                ('editors', models.ManyToManyField(blank=True, to='workshops.editor')),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshops.workshop'),
        ),
    ]
