# Generated by Django 5.0.1 on 2024-01-17 12:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Editor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("volume_editor", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("pages", models.CharField(max_length=10)),
                ("metadata", models.JSONField()),
                ("uploaded_file", models.FileField(upload_to="papers/")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workshops.author",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Workshop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("volume_number", models.CharField(max_length=10)),
                ("urn", models.CharField(max_length=50)),
                ("publication_year", models.IntegerField()),
                ("license", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=200)),
                ("location_time", models.CharField(max_length=200)),
                (
                    "secret_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "accepted_papers",
                    models.ManyToManyField(
                        related_name="accepted_papers", to="workshops.paper"
                    ),
                ),
                (
                    "editors",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workshops.editor",
                    ),
                ),
                (
                    "regular_accepted_papers",
                    models.ManyToManyField(
                        related_name="regular_accepted_papers", to="workshops.paper"
                    ),
                ),
                (
                    "short_accepted_papers",
                    models.ManyToManyField(
                        related_name="short_accepted_papers", to="workshops.paper"
                    ),
                ),
                (
                    "submitted_papers",
                    models.ManyToManyField(
                        related_name="submitted_papers", to="workshops.paper"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="paper",
            name="workshop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="workshops.workshop"
            ),
        ),
    ]
