# Generated by Django 5.0.1 on 2024-04-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='submission_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
