# Generated by Django 5.0.1 on 2024-02-29 10:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='workshop_location',
            new_name='workshop_city',
        ),
        migrations.AddField(
            model_name='editor',
            name='workshop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workshop_editors', to='workshops.workshop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='workshop_country',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workshop',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='workshops_editors', to='workshops.editor'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='workshop_begin_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='workshop_description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='workshop_end_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
