# Generated by Django 5.0.6 on 2024-06-20 11:43

import workshops.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="workshop",
            name="has_preface",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workshop",
            name="preface",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=workshops.models.Workshop.workshop_preface_file_path,
            ),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="editor_agreement",
            field=models.FileField(
                upload_to=workshops.models.Workshop.workshop_agreement_file_path
            ),
        ),
    ]
