# Generated by Django 5.0.1 on 2024-01-18 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paper",
            old_name="title",
            new_name="paper_title",
        ),
        migrations.RenameField(
            model_name="workshop",
            old_name="title",
            new_name="workshop_title",
        ),
    ]
