# Generated by Django 5.0.1 on 2024-03-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='number_accepted_papers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='number_regular_size_papers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='number_short_size_papers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='number_submitted_papers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
