# Generated by Django 5.0.1 on 2024-04-17 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='sessions',
        ),
        migrations.AddField(
            model_name='workshop',
            name='sessions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshop_sessions', to='workshops.session'),
        ),
    ]
