# Generated by Django 5.0.1 on 2024-03-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='author_university',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
