# Generated by Django 5.0.6 on 2024-07-21 10:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paper",
            options={},
        ),
    ]
