# Generated by Django 5.0.6 on 2024-06-16 10:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="author",
            name="author_uni_url",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="paper",
            name="pages",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="author_upload_secret_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
