# Generated by Django 5.0.6 on 2024-07-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="sort_order",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
