# Generated by Django 5.0.6 on 2024-06-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0002_paper_order_alter_author_author_uni_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="has_third_party_material",
            field=models.BooleanField(default=False),
        ),
    ]
