# Generated by Django 5.0.1 on 2024-03-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_alter_author_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='uploaded_file',
            field=models.FileField(null=True, upload_to='papers/'),
        ),
    ]
