# Generated by Django 5.0.6 on 2024-06-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0002_alter_author_author_uni_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
