# Generated by Django 5.0.1 on 2024-02-29 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_rename_workshop_location_workshop_workshop_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='location_time',
        ),
    ]
