# Generated by Django 5.0.1 on 2024-04-17 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_remove_workshop_sessions_workshop_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='sessions',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workshop_sessions', to='workshops.session'),
            preserve_default=False,
        ),
    ]
