# Generated by Django 5.0.6 on 2024-07-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0002_remove_workshop_openreview_url_workshop_submitted"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshop",
            name="openreview_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
