# Generated by Django 5.0.1 on 2024-01-22 12:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0002_rename_title_paper_paper_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paper",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="paper",
            name="uploaded_file",
        ),
    ]
