# Generated by Django 5.0.1 on 2024-04-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_alter_workshop_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='institution_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='total_accepted_papers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workshop',
            name='total_submitted_papers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
