# Generated by Django 5.0.6 on 2024-07-21 10:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0002_alter_paper_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paper",
            options={"ordering": ["order"]},
        ),
    ]
