# Generated by Django 5.0.1 on 2024-02-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_alter_author_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='workshop_title',
            field=models.CharField(max_length=200),
        ),
    ]
