# Generated by Django 5.0.1 on 2024-01-29 10:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0003_remove_paper_metadata_remove_paper_uploaded_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="author",
            new_name="author_name",
        ),
        migrations.AlterField(
            model_name="author",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="editors",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workshops.editor",
            ),
        ),
    ]
