# Generated by Django 5.0.1 on 2024-02-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_remove_workshop_location_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='license',
            field=models.CharField(default='License', max_length=50),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='publication_year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='volume_number',
            field=models.IntegerField(default=1000, max_length=10),
        ),
    ]
