# Generated by Django 5.0.1 on 2024-02-05 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_alter_workshop_workshop_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshops.editor'),
        ),
    ]
