# Generated by Django 5.0.1 on 2024-04-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0003_alter_editor_institution_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editor",
            name="research_group",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
