# Generated by Django 5.0.1 on 2024-03-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_alter_paper_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='papers/'),
        ),
    ]
