# Generated by Django 5.0.1 on 2024-04-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_alter_workshop_sessions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='sessions',
        ),
        migrations.AddField(
            model_name='workshop',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='workshop_sessions', to='workshops.session'),
        ),
    ]
