# Generated by Django 5.0.1 on 2024-01-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0004_rename_author_author_author_name_alter_author_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="author_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
