# Generated by Django 5.0.1 on 2024-05-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_language_alter_editor_research_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='editor_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='workshop_colocated',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
