# Generated by Django 5.0.1 on 2024-05-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0004_alter_editor_research_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="author_email",
            field=models.EmailField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="editor",
            name="editor_url",
            field=models.URLField(blank=True),
        ),
    ]
