# Generated by Django 5.0.1 on 2024-03-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_alter_workshop_license_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editor',
            name='workshop',
        ),
        migrations.AlterField(
            model_name='workshop',
            name='volume_number',
            field=models.IntegerField(default=1000),
        ),
    ]
