# Generated by Django 5.0.1 on 2024-03-08 08:27

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0004_alter_paper_uploaded_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshop",
            name="workshop_country",
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
