# Generated by Django 5.0.1 on 2024-02-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0005_alter_workshop_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='workshop_summary',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='workshop_title',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
