# Generated by Django 5.0.1 on 2024-05-03 10:36

import workshops.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0005_author_author_email_alter_editor_editor_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="editor",
            name="editor_agreement",
            field=models.FileField(
                blank=True, null=True, upload_to=workshops.models.agreement_file_path
            ),
        ),
    ]
