# Generated by Django 5.0.1 on 2024-04-17 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0005_remove_workshop_sessions_workshop_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='workshops.session'),
        ),
    ]
