# Generated by Django 5.0.1 on 2024-03-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0007_alter_editor_university_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshop",
            name="email_address",
            field=models.EmailField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
