# Generated by Django 5.0.1 on 2024-03-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0008_workshop_email_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="agreement_file",
            field=models.FileField(default=10, upload_to="agreement/"),
            preserve_default=False,
        ),
    ]
