# Generated by Django 5.0.1 on 2024-02-06 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0005_alter_author_author_name'),
        ('workshops', '0008_workshop_editor'),
    ]

    operations = [
    ]
