# Generated by Django 5.0.1 on 2024-04-18 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0008_alter_paper_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshops.session'),
        ),
    ]
