# Generated by Django 5.0.1 on 2024-03-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0009_paper_agreement_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="agreement_file",
            field=models.FileField(blank=True, null=True, upload_to="agreement/"),
        ),
    ]
