# Generated by Django 3.2.23 on 2024-03-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0010_alter_paper_agreement_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='agreement_file',
            field=models.FileField(blank=True, null=True, upload_to='agreement/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='papers/%Y/%m/%d/'),
        ),
    ]
