# Generated by Django 5.0.1 on 2024-02-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0010_remove_workshop_editor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='editors',
        ),
        migrations.AddField(
            model_name='workshop',
            name='editor_1',
            field=models.CharField(default='editor_1', max_length=50),
        ),
        migrations.AddField(
            model_name='workshop',
            name='editor_2',
            field=models.CharField(default='editor_2', max_length=50),
        ),
        migrations.AddField(
            model_name='workshop',
            name='editor_3',
            field=models.CharField(default='editor_3', max_length=50),
        ),
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
