# Generated by Django 5.0.1 on 2024-02-07 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0011_remove_workshop_editors_workshop_editor_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_editor', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='editor_1',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='editor_2',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='editor_3',
        ),
        migrations.AddField(
            model_name='workshop',
            name='editors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workshops.editor'),
        ),
    ]
