# Generated by Django 3.2.23 on 2024-03-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0012_auto_20240324_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='workshop',
        ),
        migrations.AlterField(
            model_name='paper',
            name='agreement_file',
            field=models.FileField(blank=True, null=True, upload_to='agreement/'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='papers/'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='license',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='publication_year',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='volume_number',
            field=models.IntegerField(max_length=200),
        ),
    ]
