# Generated by Django 5.0.1 on 2024-02-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0012_editor_remove_workshop_editor_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='editors',
        ),
        migrations.AddField(
            model_name='workshop',
            name='editors',
            field=models.ManyToManyField(blank=True, to='workshops.editor'),
        ),
    ]
