# Generated by Django 5.0.1 on 2024-02-07 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0013_remove_workshop_editors_workshop_editors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editor',
            old_name='volume_editor',
            new_name='name',
        ),
    ]
