# Generated by Django 3.2.23 on 2024-03-24 13:59

from django.db import migrations, models
import django.db.models.deletion
import workshops.models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0013_auto_20240324_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='workshop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='workshops.workshop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paper',
            name='agreement_file',
            field=models.FileField(blank=True, null=True, upload_to=workshops.models.agreement_file_path),
        ),
        migrations.AlterField(
            model_name='paper',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to=workshops.models.paper_upload_path),
        ),
    ]
