# Generated by Django 3.2.23 on 2024-03-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0014_auto_20240324_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='volume_number',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
