# Generated by Django 5.0.1 on 2024-02-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0014_rename_volume_editor_editor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='uploaded_file',
            field=models.FileField(default='yes', upload_to='papers/'),
            preserve_default=False,
        ),
    ]
