# Generated by Django 5.0.3 on 2024-03-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0015_alter_workshop_volume_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='publication_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='volume_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
