# Generated by Django 5.0.1 on 2024-02-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0015_paper_uploaded_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshop",
            name="location_time",
            field=models.CharField(max_length=300),
        ),
    ]
