# Generated by Django 5.0.1 on 2024-02-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0015_paper_uploaded_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='regular_accepted_papers',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='short_accepted_papers',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='submitted_papers',
        ),
        migrations.AddField(
            model_name='workshop',
            name='authors',
            field=models.ManyToManyField(related_name='workshops_authored', to='workshops.author'),
        ),
    ]
