# Generated by Django 5.0.1 on 2024-02-21 11:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0018_paper_secret_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="secret_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
